### PR TITLE
Initial commit for Module 15

### PR DESCRIPTION
**Pull request by mwand**

### CODE REVIEW

**Comment by abhutta0** [comment]
do we really need the outline slide (#3)?? Perhaps we should organized it same way we organized l14. i.e., in modules, all in one slide deck. Say modules 15.1, 2, 3 .... and insert empty slide before each section.
I actually liked the public-private-key image we had used (with some updates), amazon one.
Formatting nitpick: different headings have different font sizes
There is a lot of material but I will have to present in a cohesive manner. Can't think of one right now.
We start by taking about 5 vulnerabilities but end up with 4.
3rd item is outline is discussed where?
I will have to review these again in the morning with clearer head.

**Comment by abhutta0** [comment]
On second read .... I think lecture looks good. Needs some minor updates:
Slide #7: Suggest adding the picture of "house with glass windows" back in. That way we can discuss some options to make the house secure.
Slide 35: Suggest adding the slide with Amazon/CA public private key animation here before slide that discusses CA compromise.
Still need to make sure that we correct the numbers (of vulnerabilities) in the last slide (says 4), and Slide 14 (list of vulnerabilities we will discuss, says 5) and Slide 2 (learning objectives, says 5)
Rest lrtm
I use this on Monday for lecture.

**Comment by mwand** [comment]
> On second read .... I think lecture looks good. Needs some minor updates:
> Slide https://github.com/neu-se/CS4530-Fall-2023/pull/7: Suggest adding the picture of "house with glass windows" back in. That way we can discuss some options to make the house secure.

Done.  I always found that slide to be a distraction, but I've put it in so you can have it.
> Slide 35: Suggest adding the slide with Amazon/CA public private key animation here before slide that discusses CA compromise.

Restored. I always found the animation confusing--  the text on the slide before is intended to be a clearer version.

> Still need to make sure that we correct the numbers (of vulnerabilities) in the last slide (says 4), and Slide 14 (list of vulnerabilities we will discuss, says 5) and Slide 2 (learning objectives, says 5)

I think I got it this time.   Also put in a title slide introducing Outline item # 3.
> Link to OWASP website is useful We should add it in slide # 14

It's already on the module page.  I added some text in the speaker's notes to slide 14.   Also updated the list from 2017 to 2021 (the most recent version).
> Rest lrtm
> I use this on Monday for lecture.
I hope it's now in usable shape for you.

**Comment by abhutta0** [comment]
apart from two minor issues (1) different font sizes for headings, (2) last slide still says 4, lgtm

**Comment by mwand** [comment]
ok,ok.   Fixed the last slide.   Fixed some of the bad headings.  (Stupid Keynote formats).  That's all I can do tonight.
G'nite.

**Pull request merged**
