### PR TITLE
initial commit for M07-08

### PR DESCRIPTION
**Pull request by mwand**
Major rewrite of the REACT materials; updated to next.js.   Alas, no activity for module 08.  If anyone wants to create one, feel free.

### CODE REVIEW

**Comment by mwand** [comment]
@anurag-arasan Please double check to make sure the activity works for you.

**Review by anurag-arasan — APPROVED** [review]
Was able to download, build, and complete the assignment with little issue.

**Comment by abhutta0** [comment]
Module 7:
Slide 27 could use some more text (and notes) with extra detail or explanation.... why are values same? perhaps re-state the point from previous slide.
Slide 30 could also use extra text in slide (and notes), in case we don't do a live demo!
For Slide 32, we should perhaps make a gif (with demo) and embed that in slide.
Slide 34 could use some explanation as to why "key" is needed. In old slides there was a neat demo of this.... with like and delete buttons
Rest LGTM

Module 8
We should add slides 8 and 10 from Spring 2023 in this semester's slides. Those provide a nice intro before we start looking at the examples.
Rest LGTM

**Comment by abhutta0** [comment]
We also need a tutorial for React ... I will create PR and then we should update/publish that with this PR.

**Comment by mwand** [comment]
On Mon, Sep 25, 2023 at 3:28 PM Adeel A. Bhutta ***@***.***>
wrote:

> Module 7:
> Slide 27 could use some more text (and notes) with extra detail or
> explanation.... why are values same? perhaps re-state the point from
> previous slide.
>
Added text in speaker notes

> Slide 30 could also use extra text in slide (and notes), in case we don't
> do a live demo!
>
Ditto.

> For Slide 32, we should perhaps make a gif (with demo) and embed that in
> slide.
>
I don't have the time to do that, sorry.

> Slide 34 could use some explanation as to why "key" is needed. In old
> slides there was a neat demo of this.... with like and delete buttons
>
The old version was more detailed than was useful for the students, I
think.  Slide 35 is a demo of bad behavior.

> Rest LGTM
>
> Module 8
> We should add slides 8 and 10 from Spring 2023 in this semester's slides.
> Those provide a nice intro before we start looking at the examples.
>
Redid intro to add simple example before the real one.  Added some slides &
animations to illustrate.  I hope this is better.

**Pull request merged**
