### PR TITLE
updated slides for technical debt

### PR DESCRIPTION
**Pull request by abhutta0**

### CODE REVIEW

**Comment by mwand** [comment]
Several tweaks to slides: 7,8,26,27. (added some words, also one animation,s8).
Need to add the links that are on the slides to the module page.
s29: what is meant by "not in Py3 => not used"  (need to add explanation to Speaker Notes)
s30: speaker notes need to explain what is uwsgi/django? what is celery?.   Why do we have cpu measured on one, memory on the other?

**Comment by abhutta0** [comment]
Added link to module page. Also added speaker notes
For slide 30: Instagram uses uwsgi/django and celery! These benchmarks just mention the techs they internally use.

**Comment by mwand** [comment]
module page still says "In this module, you will learn **to**.
Might want to mention that what hack does is called "gradual typing"
I'm still not clear on "not in Py3 => not used"  .   Is the idea that they eliminated the use of any Py2 packages that were dropped in Py3?  So they'd have to reimplement the portions of those packages that were in (Py2 and not Py3)?  
thanks for the explanation on slide 30.  If it's good enough for you, it's good enough for now.

Otherwise, lgtm.

**Comment by abhutta0** [comment]
Yes, instagram switched from python2 to python3. During that change, they re-wrote all python2 code in python3. Any external libraries were also updated in same way. During this transition, the rules was, anything not in python3, won't be added to the codebase. The link provides more detail / context for this effort.
I will review the learning objectives and merge.

**Pull request merged**
