### PR TITLE
updated module 02 slides and old activity

### PR DESCRIPTION
**Pull request by iamabhutta**
updated slides
using same activity for now. Should we consider updating it to something new?

TODO: check if starter code works with the new instructions in IDE tutorial.
TODO: merge module01 before merging this.

### CODE REVIEW

**Comment by mwand** [comment]
When I switch to this branch, the web page fails to build, due to missing files.  Can't review it until the web page builds, sorry.

**Comment by abhutta0** [comment]
You should be able to pull and then review slides in the branch without building the site.

**Comment by mwand** [comment]
That is true.  I will do that much.

**Comment by mwand** [comment]
- Slides are ok.
- Activities/  .. the zip file contained a bogus file from another activities.  I've rebuilt it and pushed. Please check to see that it's right
- Examples/  normally contains the examples from the lecture, but here the examples are the same as the activities.   Need to make sure that the l2.md points to the right file.
- lectures/ld2.md  -- not checked

**Pull request merged**
