### PR TITLE
first draft of new Ethics slides

### PR DESCRIPTION
**Pull request by mwand**
An entirely new lesson, based in large part of Christo Wilson's _value-based design_ slides.   I didn't see any need to belabor all the terrible things that computers do-- these days I think everybody knows most of these.

(Ahh, I forgot to mention GPT3 -- I will do that in the next commit).

I think the slides tell a coherent story, with a coherent action plan for students.

What do you think?

### CODE REVIEW

**Comment by mwand** [comment]
FYI:  all I've done here is to add Slides/Module 17 Ethics.pptx .  No pdf, no update to module page, etc.

**Comment by abhutta0** [comment]
what does DM mean in notes of Slide 7.
I am not sure if we need to go over such detail of Value Sensitive design, do we? Perhaps cut it down to two or three slides and highlight the important points only.
I would suggest removing the exercise slide at the end or replacing with something else.
Rest lgtm

I have added module page and pdf file for now.

**Comment by mwand** [comment]
I have no idea with DM means; those are just the speakers notes that were in the file.  I will do speakers' notes in the next draft.

In case it wasn't clear, my intention was to ditch everything past slide 21.  It felt like everything past that point was repetitive or useless (eg Codes of Conduct).

Thanks for setting up the module page.  I will add Resource links.

**Comment by abhutta0** [comment]
> I have no idea with DM means; those are just the speakers notes that were in the file. I will do speakers' notes in the next draft.
> 
> In case it wasn't clear, my intention was to ditch everything past slide 21. It felt like everything past that point was repetitive or useless (eg Codes of Conduct).
> 
> Thanks for setting up the module page. I will add Resource links.

I actually like the slides after #21 more. :)

**Comment by mwand** [comment]
I've moved the slides with the examples back into the main sequence, as slides 4-12, but I've made them hidden; you can unhide them.

I'd prefer not to release slides that neither of us like.   If you are ok with delivering slides 1-31 (with some of the slides unhidden), then I will delete slides 32-end, and remove the "draft" from this PR.

If you want to talk about this in more detail, we can do it at our meeting tomorrow, ok?

**Comment by abhutta0** [comment]
ok to delete slides 32 onwards ... perhaps one slide for microsoft stuff can help?
You can leave 4-12 as hidden, I can unhide for my lectures. Rest lgtm.
I think I already removed "draft" from PR.

**Comment by mwand** [comment]
Add MS slides where they might go (but hidden).
Will merge to main now.

**Pull request merged**
