### PR TITLE
PR for module 03: design principles

### PR DESCRIPTION
**Pull request by mwand**
@aryanjain28 @Leelakrishna2091997 Please run the activity with the F23 official versions of typescript, jest, etc.

### CODE REVIEW

**Comment by mwand** [comment]
Also, note that the ip1 here is the one from last semester.  Presumably it will be overwritten when the IP1 PR (PR #2) gets merged with main.

**Comment by abhutta0** [comment]
Slides look good.
This is ready to merge after you can check/update activity files @mwand 
Let's not reuse old IP1/IP2 files anymore ...

**Comment by Leelakrishna2091997** [comment]
I've tested the activity its working fine. Tested with versions as follows:
- Node - 18.17
- Tsc - 5.2.2
- npm - 9.6.7

**Review by Leelakrishna2091997 — APPROVED** [review]
The functionalities are working fine reviewed on node version 18.

**Review by aryanjain28 — APPROVED** [review]
Activity working fine with the required versions.

**Pull request merged**
