### PR TITLE
initial version of IDE setup

### PR DESCRIPTION
**Pull request by abhutta0**
SP23 version. Need to update to requirements of new codebase.

### CODE REVIEW

**Comment by Leelakrishna2091997** [comment]
In the installation of nvm on mac, if we follow through curl command its working fine. With wget, we expect it has be installed before executing this command "wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash".

Please correct me if my observation is wrong.

**Comment by Leelakrishna2091997** [comment]
Should we include the screenshots and references to run, execute and debug the application using IDE in this tutorial .

**Review by aryanjain28 — COMMENTED** [review]
Everything looks good to me. I was able to download and install the libraries and tools using the ReadMe.

Tested on:
~ Windows 10
~ Mac M2

**Comment by Leelakrishna2091997** [comment]
I've followed the set of steps mentioned in the document and successfully able to setup IDE and application. 

Tested on:
- Mac
- Windows

**Review by Leelakrishna2091997 — APPROVED** [review]

**Pull request merged**
