### PR TITLE
Module 06 agile

### PR DESCRIPTION
**Pull request by abhutta0**
slides from last fall/spring. updated link to survey and created Canvas assignment.

### CODE REVIEW

**Comment by mwand** [comment]
In Lesson 6.3, slide 8, there's a link in the speaker notes.   I've noticed that you can't cut-and-paste from the speaker notes during a presentation, so it's not possible to drop the link in chat.   Need to add this link in the Resources section of the lecture page.

**Comment by mwand** [comment]
There are also a few places where a slide could be deleted or skipped without loss, but it's too close to deadline to think about these.  Let's leave a pointer to this for next time.

**Comment by mwand** [comment]
Doing Async + Agile in one week is a sprint in itself, but I don't have any good ideas about what to cut.

**Comment by mwand** [comment]
As before, the slides look good to me, but I have NOT checked the lecture slides to make sure the links work, and I have NOT checked the activity to make sure that it still works.  Can we have a TA do this?

**Comment by abhutta0** [comment]
I will check mod6 slides to see if we can cut something ... there is no activity for mod6

**Comment by abhutta0** [comment]
> there's a link in the speaker notes. I've noticed that you can't cut-and-paste from t

The link is also in the slide and you should be able to click on it during presentation. I can add that to resources for the module page

**Pull request merged**
