### PR TITLE
initial slides for CD lecture

### PR DESCRIPTION
**Pull request by abhutta0**
Comment from Sp23: very long lecture .... might want to see if something can be cut.

### CODE REVIEW

**Comment by abhutta0** [comment]
removed slides 49-50 and added the details in notes of slide 48.

**Comment by mwand** [comment]
In the graph on slide 4-5, why is Code Review *after* Commit/Integration?

**Comment by abhutta0** [comment]
I have re-arranged the slides, mostly using similar approach as Mitch suggested. Hopefully the order matches the narrative

**Comment by abhutta0** [comment]
> In the graph on slide 4-5, why is Code Review _after_ Commit/Integration?

May be because its mostly done for updates?

**Comment by abhutta0** [comment]
@mwand if you still feel that we should move code review slides before, I can do that.

**Comment by abhutta0** [comment]
I have unhid the slides for Facebook CI pipeline. I think it is useful example. If you don't want to discuss those, you can perhaps hide them during your lecture?

**Comment by mwand** [comment]
lgtm.   I may tweak them a little (like adding some animated boxes to slide 11) if I have time between now and 6pm tomorrow.  But I won't hide or unhide anything :)

**Comment by abhutta0** [comment]
Should I merge then or wait for you?

**Pull request merged**
